services:
  db:
    image: mysql:8.0
    container_name: animal_mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: animal_db
      MYSQL_ROOT_PASSWORD: root123 # Mật khẩu
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/database_scripts:/docker-entrypoint-initdb.d

volumes:
  db_data: